# config.py

disallowed_sections = [
    "salvation",
    "alexander scourby",
    "hymns",
    "other music",
    "psalms",
    "volume 1",
    "volume 2",
    "volume 3",
    "volume 4",
    "volume 5",
    "volume 6",
]

existing_video_ids = []  # connect this to DB

section_replacements = {
    # Word pairs stuck together (lowercase)
    r"(clips|sermons|seminar)(pastor|bro)": r"${1} ${2}",
    r"(winning)(motivation|tips)": r"${1} ${2}",
    r"(tribulation)(moments)": r"${1} ${2}",
    r"(by)(pastor)": r"${1} ${2}",
    r"(lord|james)(conference)": r"${1} ${2}",
    r"(conference|class)(\d+)": r"${1} ${2}",
    r"(bro\.)": r"brother",
    r"\b(bro)\b": r"brother",
    # Year suffix: adds space between word and year
    r"([a-z]+)(\d{4})": r"${1} ${2}",
}

title_replacements = {
    r"(bro\.)": r"brother",
    r"\b(bro)\b": r"brother",
    # Year suffix: adds space between word and year
    r"([a-z]+)(\d{4})": r"${1} ${2}",
}

# section_preacher_replacements = {
#     r"[/w ]+ \d{4}": r"evaluate",
#     r"^(sermons|sermon clips|seminar|short videos by) (bro\.|brother|pastor) (\w+) (\w+)$": r"${2} ${3} ${4}",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor anderson$": r"pastor steven anderson",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor jimenez$": r"pastor roger jimenez",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor shelley$": r"pastor jonathan shelley",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor awes$": r"pastor dillon awes",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor thompson$": r"pastor aaron thompson",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor taverner$": r"pastor ian taverner",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor sepulveda$": r"pastor kevin sepulveda",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor stucky$": r"pastor matthew stucky",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor mejia$": r"pastor bruce mejia",
#     r"^(sermons|sermon clips|seminar|short videos by) pastor ressl$": r"pastor corbin ressl",
#     # replace nulls with "unknown"
# }

preacher_names_replacements = {
    "pastor anderson": "pastor steven anderson",
    "steven anderson": "pastor steven anderson",
    "pastor shelley": "pastor jonathan shelley",
    "jonathan shelley": "pastor jonathan shelley",
    "pastor jimenez": "pastor roger jimenez",
    "roger jimenez": "pastor roger jimenez",
    "pastor thompson": "pastor aaron thompson",
    "aaron thompson": "pastor aaron thompson",
    "brother dillon awes": "pastor dillon awes",
    "dillon awes": "pastor dillon awes",
    "pastor awes": "pastor dillon awes",
    "evangelist mejia": "pastor bruce mejia",
    "pastor mejia": "pastor bruce mejia",
    "bruce mejia": "pastor bruce mejia",
    "brother stucky": "pastor matthew stucky",
    "matthew stucky": "pastor matthew stucky",
    "deacon ressl": "pastor corbin ressl",
    "corbin ressl": "pastor corbin ressl",
    "pastor ressl": "pastor corbin ressl",
    "ian taverner": "pastor ian taverner",
    "kevin sepulveda": "pastor kevin sepulveda",
    "pastor reyes": "pastor enrique reyes",
    "pastor bougardt": "pastor oscar bougardt",
    "pastor webb": "pastor webb",  # what is his first name?
    "deacon gonzalez": "deacon oliver gonzalez",
    "chris segura": "brother chris segura",
    "brother segura": "brother chris segura",
    "brother alex larson": "brother alexander larson",
    "brother alexander larson": "brother alexander larson",
    "alexander larson": "brother alexander larson",
    "kevin roe": "brother kevin roe",
    "raymond cooper": "brother raymond cooper",
    "daniel reiter": "brother daniel reiter",
    "anselm urban": "brother anselm urban",
    "ben naim": "brother ben naim",
    "caleb akinosho": "brother caleb akinosho",
}

section_preacher_map = {
    "fbbf 2019": "evaluate",
    "fbbf 2021": "evaluate",
    "fbc 2019": "evaluate",
    "fbc 2020": "evaluate",
    "fbc 2021": "evaluate",
    "fwbc missions conference 2023": "evaluate",
    "fwbc missions conference 2024": "evaluate",
    "fwbc preaching class 2022": "evaluate",
    "heritage of the lord conference 2022": "evaluate",
    "king james conference 2023": "evaluate",
    "masa 2019": "evaluate",
    "marching to zion conference 2018": "evaluate",
    "next generation youth rally 2023": "evaluate",
    "prophesy conference 2015": "evaluate",
    "red hot preaching conference 2016": "evaluate",
    "red hot preaching conference 2017": "evaluate",
    "red hot preaching conference 2018": "evaluate",
    "red hot preaching conference 2019": "evaluate",
    "red hot preaching conference 2020": "evaluate",
    "red hot preaching conference 2021": "evaluate",
    "red hot preaching conference 2022": "evaluate",
    "red hot preaching conference 2023": "evaluate",
    "red hot preaching conference 2024": "evaluate",
    "sermon clips bro. dillon awes": "pastor dillon awes",
    "sermon clips bro. chris segura": "brother chris segura",
    "sermon clips pastor matthew stucky": "pastor matthew stucky",
    "sermon clips pastor corbin ressl": "pastor corbin ressl",
    "sermon clips pastor steven anderson": "pastor steven anderson",
    "sermon clips pastor ian taverner": "pastor ian taverner",
    "sermon clips pastor roger jimenez": "pastor roger jimenez",
    "sermon clips pastor bruce mejia": "pastor bruce mejia",
    "sermon clips pastor jonathan shelley": "pastor jonathan shelley",
    "sermon clips pastor aaron thompson": "pastor aaron thompson",
    "sermons pastor dillon awes": "pastor dillon awes",
    "sermons bro. dillon awes": "pastor dillon awes",  # TODO need to make this more flexible, perhaps using regex
    "sermons bro. raymond cooper": "brother raymond cooper",
    "sermons bro. ben naim": "brother ben naim",
    "sermons bro. chris segura": "brother chris segura",
    "sermons pastor matthew stucky": "pastor matthew stucky",
    "sermons pastor corbin ressl": "pastor corbin ressl",
    "sermons pastor steven anderson": "pastor steven anderson",
    "sermons pastor ian taverner": "pastor ian taverner",
    "sermons pastor roger jimenez": "pastor roger jimenez",
    "sermons pastor bruce mejia": "pastor bruce mejia",
    "sermons pastor kevin sepulveda": "pastor kevin sepulveda",
    "sermons pastor jonathan shelley": "pastor jonathan shelley",
    "sermons pastor aaron thompson": "pastor aaron thompson",
    "soul winning motivation": "unknown",
    "seminar pastor anderson": "pastor steven anderson",
    "seminar pastor jimenez": "pastor roger jimenez",
    "seminar pastor shelley": "pastor jonathan shelley",
    "soul winning tips": "evaluate",
    "creation moments": "unknown",
    "day of the dead moments": "evaluate",
    "topics for dummies": "brother alexander larson",
    "hindu moments": "evaluate",
    "israel moments": "evaluate",
    "kjv minutes": "evaluate",
    "mormon moments": "evaluate",
    "post tribulation moments": "evaluate",
    "short videos by pastor jimenez": "pastor roger jimenez",
    "thessalonian moments": "evaluate",
    "trinity moments": "evaluate",
    "documentaries": "unknown",
    "trailers": "unknown",
    "creation": "unknown",
    "interviews": "unknown",
    "baptist bias": "unknown",
    "olive crown": "unknown",
    "rod of iron": "unknown",
    "sword of the spirit": "unknown",
    "true born sons": "unknown",
    "the sword drill": "unknown",
    "uncensored": "unknown",
    "landmarks": "unknown",
    "other videos": "unknown",
}
